openapi: 3.0.3
info:
  title: LiveZone API
  version: 1.0.0
  description: API to manage zones and guests in a simulated live zone system.

servers:
  - url: http://localhost:8080

paths:
  /zones:
    get:
      summary: Get all zones
      tags:
        - Zones
      responses:
        '200':
          description: A list of all zones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zone'

  /zones/occupancy/{id}:
    get:
      summary: Get occupancy info for a zone
      tags:
        - Zones
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
          description: ID of the zone
      responses:
        '200':
          description: Zone occupancy details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZoneStatusDto'
        '404':
          description: Zone not found

  /zones/averageTimeSpent/{id}:
    get:
      summary: Get average time spent in a zone
      tags:
        - Zones
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Average time spent in the zone
          content:
            application/json:
              schema:
                type: number
                format: float
        '204':
          description: No data for this zone

  /zones/hotspots:
    get:
      summary: Get all full zones (hotspots)
      tags:
        - Zones
      responses:
        '200':
          description: List of hotspot zones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ZoneStatusDto'
        '204':
          description: No hotspots found

  /zones/changeCapacity/{id}?newCapacity=1:
    post:
      summary: Change zone capacity
      tags:
        - Zones
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
        - in: query
          name: newCapacity
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Capacity changed successfully
        '204':
          description: Could not change capacity

  /guests:
    get:
      summary: Get all guests
      tags:
        - Guests
      responses:
        '200':
          description: A list of all guests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Guest'

  /guests/simulate-move:
    post:
      summary: Simulate guest movements
      tags:
        - Guests
      responses:
        '200':
          description: Guests moved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Guest'
        '204':
          description: No guests were moved

components:
  schemas:
    Zone:
      type: object
      properties:
        zoneId:
          type: string
        zoneName:
          type: string
        capacity:
          type: integer
        currentGuestCount:
          type: integer
        adjacentZoneWeights:
          type: object
          additionalProperties:
            type: integer

    Guest:
      type: object
      properties:
        guestId:
          type: string
        currentZoneId:
          type: string
        timeAlive:
          type: integer

    ZoneStatusDto:
      type: object
      properties:
        zoneId:
          type: string
        zoneName:
          type: string
        capacity:
          type: integer
        currentGuestCount:
          type: integer
        status:
          type: string
