openapi: 3.0.0
info:
  title: Zone Simulation API
  description: API for monitoring and simulating guests in different zones
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /zones:
    get:
      summary: Get all zones
      responses:
        '200':
          description: Returns all zone objects

  /zones/occupancy/{id}:
    get:
      summary: Get occupancy status for a specific zone
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Zone occupancy details

  /zones/hotspots:
    get:
      summary: Get all crowded or full zones
      responses:
        '200':
          description: List of hotspots

  /zones/averageTimeSpent/{id}:
    get:
      summary: Get average time spent in a zone
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Average time spent in the zone

  /zones/change-capacity/{id}:
    post:
      summary: Change the capacity of a zone
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
        - name: newCapacity
          in: query
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Capacity changed successfully

  /guests:
    get:
      summary: Get all guests in the park
      responses:
        '200':
          description: List of guests

  /guests/simulate-move:
    post:
      summary: Simulate moving 5 random guests
      responses:
        '200':
          description: Move simulation complete
        '500':
          description: Server error during simulation

components:
  schemas:
    Zone:
      type: object
      properties:
        zoneId:
          type: string
        zoneName:
          type: string
        capacity:
          type: integer
        currentGuestCount:
          type: integer
        threshold:
          type: number
          format: float
        averageDuration:
          type: number
          format: float

    Guest:
      type: object
      properties:
        guestId:
          type: string
        currentZoneId:
          type: string
        timeToLive:
          type: integer
        timeAlive:
          type: integer

    ZoneStatusDto:
      type: object
      properties:
        zoneId:
          type: string
        zoneName:
          type: string
        capacity:
          type: integer
        currentGuestCount:
          type: integer
        occupancyPercent:
          type: number
          format: float
        status:
          type: string
          enum: [OK, CROWDED, FULL]
