openapi: 3.0.3
info:
  title: Zone & Guest Simulation API
  description: API for simulating guests and monitoring zone occupancy in a virtual park.
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /zones:
    get:
      summary: Get all zones
      responses:
        '200':
          description: A list of all zones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Zone'

  /zones/occupancy/{id}:
    get:
      summary: Get occupancy status of a zone
      parameters:
        - name: id
          in: path
          required: true
          description: Zone ID
          schema:
            type: string
      responses:
        '200':
          description: Zone status details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ZoneStatusDto'
        '404':
          description: Zone not found

  /zones/averageTimeSpent/{id}:
    get:
      summary: Get average time spent in a zone
      parameters:
        - name: id
          in: path
          required: true
          description: Zone ID
          schema:
            type: string
      responses:
        '200':
          description: Average duration
          content:
            application/json:
              schema:
                type: number
                format: float
        '404':
          description: Zone not found

  /zones/hotspots:
    get:
      summary: Get hotspots (zones that are crowded or full)
      responses:
        '200':
          description: A list of crowded or full zones
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ZoneStatusDto'

  /zones/change-capacity/{id}:
    post:
      summary: Change the capacity of a zone
      parameters:
        - name: id
          in: path
          required: true
          description: Zone ID
          schema:
            type: string
        - name: newCapacity
          in: query
          required: true
          description: New capacity for the zone
          schema:
            type: integer
      responses:
        '200':
          description: Capacity changed successfully
        '400':
          description: Invalid input or zone cannot shrink

  /guests:
    get:
      summary: Get all active guests
      responses:
        '200':
          description: A list of all current guests
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Guest'

  /guests/simulate-move:
    post:
      summary: Simulate guest movement
      responses:
        '200':
          description: Guest movement simulated
        '500':
          description: Server error during simulation

components:
  schemas:
    Zone:
      type: object
      properties:
        zoneId:
          type: string
        zoneName:
          type: string
        capacity:
          type: integer
        currentGuestCount:
          type: integer
        threshold:
          type: number
          format: float
        averageDuration:
          type: number
          format: float

    Guest:
      type: object
      properties:
        guestId:
          type: string
        currentZoneId:
          type: string
        timeToLive:
          type: integer
        timeAlive:
          type: integer

    ZoneStatusDto:
      type: object
      properties:
        zoneId:
          type: string
        zoneName:
          type: string
        capacity:
          type: integer
        currentGuestCount:
          type: integer
        occupancyPercent:
          type: number
          format: float
        status:
          type: string
          enum: [OK, CROWDED, FULL]
